//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessGame {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.TextBox TBNumber;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl AnswerLbl;
		
		protected System.Web.UI.WebControls.Button VerifyBtn;
		
		protected System.Web.UI.WebControls.Button TryAgainBtn;
	}
}
